const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../src/routes/admin.js'),'utf8');
const start = source.indexOf("router.post('/patients/:id/health-records/import'");
const end = source.indexOf('// ── GET /api/admin/patients/:id', start);
const user={_id:'p',name:'测试客户',idNumber:'TEST-ID',tenantId:'tenant'};
function setup(found=user, duplicate=false){let handler;const writes=[];const context={router:{post:(path,auth,fn)=>{assert.equal(auth,'admin-auth');handler=fn}},adminAuth:'admin-auth',User:{findOne:filter=>{assert.deepEqual(JSON.parse(JSON.stringify(filter)),{_id:'p',isDeleted:{$ne:true}});return {select:()=>({lean:async()=>found})}}},HealthRecord:{exists:async()=>duplicate,insertMany:async docs=>writes.push(...docs)},calcHealthRecordStatus:()=> 'normal'};vm.runInNewContext(source.slice(start,end),context);return {writes,run:async(rows,preview=true)=>{let code=200,body;await handler({params:{id:'p'},admin:{_id:'admin',name:'管理员',role:'superadmin',tenantId:'tenant'},body:{rows,preview,fileName:'test.csv'}},{status(n){code=n;return this},json(x){body=x}});return {code,body}}}}
const row={idNumber:'TEST-ID',name:'测试客户',recordedAt:'2024-01-15 08:30',type:'体重',value:'70'};
test('admin preview validates ownership without writes',async()=>{const s=setup();const r=await s.run([row,{...row,idNumber:'WRONG'},{...row,name:'WRONG'}]);assert.equal(r.body.data.summary.ready,1);assert.equal(r.body.data.summary.error,2);assert.equal(s.writes.length,0)});
test('confirmed import preserves admin provenance and rejects same-file duplicates',async()=>{const s=setup();const r=await s.run([row,row],false);assert.equal(r.body.data.imported,1);assert.equal(r.body.data.summary.duplicate,1);assert.equal(s.writes[0].recordedBy.staffId,'admin');assert.equal(s.writes[0].tenantId,'tenant');assert.equal(s.writes[0].recordedAt.toISOString(),'2024-01-15T00:30:00.000Z')});
test('database duplicates and deleted customers cannot be imported',async()=>{assert.equal((await setup(user,true).run([row],false)).code,400);assert.equal((await setup(null).run([row],false)).code,404)});
test('staff import endpoint is retired',()=>{assert.ok(!fs.readFileSync(require.resolve('../src/routes/staff.js'),'utf8').includes("router.post('/patients/:id/health-records/import'"))});
