const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const policy=require('../../shared/annualServiceReminder.cjs'),logic=require('../src/utils/annualServiceRecommendation');
const now=new Date('2026-10-01T16:01:00Z');
const row={_id:'r',status:'published',response:'none',followUpReminderEnabled:true,plannedFollowUpDate:'2026-10-02',patientId:{_id:'p',name:'示例'},planId:{_id:'plan',year:2026}};
test('Beijing midnight controls due and overdue independently of server timezone',()=>{assert.equal(policy.day(now),'2026-10-02');assert.equal(policy.actionable(row,now),true);assert.equal(policy.todo(row,now).overdue,false);assert.equal(policy.actionable(row,new Date('2026-10-01T15:59:59Z')),false);assert.equal(policy.todo({...row,plannedFollowUpDate:'2026-10-01'},now).overdue,true)});
test('legacy, unpublished, future, declined and completed rows do not become reminders',()=>{for(const change of [{followUpReminderEnabled:undefined},{followUpReminderEnabled:false},{status:'draft'},{plannedFollowUpDate:'2026-10-03'},{plannedFollowUpDate:''},{response:'declined'},{handledAt:now}])assert.equal(policy.actionable({...row,...change},now),false)});
test('interest retains original reminder identity and one source when date is also due',()=>{const scheduled=policy.todo(row,now),interested=policy.todo({...row,response:'interested',respondedAt:now},now);assert.equal(scheduled.id,interested.id);assert.equal(interested.priority,1);assert.match(scheduled.link,/recommendationId=r#service-recommendation-r/);assert.equal(policy.actionable({...row,followUpReminderEnabled:false,response:'interested'},now),true)});
test('opt-in requires a valid date and internal flag is never sent to customer',()=>{const base={finding:'问题',evidence:'依据',recommendation:'服务',plannedFollowUpDate:'2026-10-02'};assert.equal(logic.normalizeRecommendationInput(base).followUpReminderEnabled,false);const enabled=logic.normalizeRecommendationInput({...base,followUpReminderEnabled:true});assert.equal(enabled.followUpReminderEnabled,true);assert.equal(logic.normalizeRecommendationInput({...base,plannedFollowUpDate:'',followUpReminderEnabled:true}).followUpReminderEnabled,false);assert.throws(()=>logic.normalizeRecommendationInput({...base,followUpReminderEnabled:'true'}));assert.equal(logic.customerRecommendation(enabled).followUpReminderEnabled,undefined)});
const src=fs.readFileSync(require.resolve('../src/routes/staff'),'utf8');const start=src.indexOf("router.post('/annual-plans/:planId/service-recommendations/:recommendationId/handle'");const end=src.indexOf("router.get('/patients/:id/annual-plan'",start);
async function handle(role,{visible=true,exists=true,note='已联系客户'}={}){let fn,filter,writes=0;vm.runInNewContext(src.slice(start,end),{router:{post:(_p,_auth,h)=>fn=h},staffAuth:()=>{},accessibleRecommendationPlan:async(req,res)=>{if(!visible){res.status(403).json({success:false});return null}return {_id:'plan'}},AnnualServiceRecommendation:{findOneAndUpdate:async(f,u)=>{filter=f;if(!exists)return null;writes++;return {...row,...u.$set}}},require:()=>policy,Date,String});const res={code:200,status(c){this.code=c;return this},json(body){this.body=body;return this}};await fn({staff:{role,_id:'actor'},params:{recommendationId:'r'},body:{note}},res);return {res,filter,writes}}
test('actual completion handler keeps role and customer restrictions',async()=>{for(const role of ['healthManager','healthPlanner','nutritionist']){const r=await handle(role);assert.equal(r.res.code,403);assert.equal(r.writes,0)}const hidden=await handle('familyDoctor',{visible:false});assert.equal(hidden.res.code,403);assert.equal(hidden.writes,0)});
test('actual completion handler checks pending source atomically, rejects empty and repeated handling',async()=>{const r=await handle('familyDoctor');assert.equal(r.writes,1);assert.equal(r.filter.handledAt,null);assert.equal(r.filter.status,'published');assert.equal(r.filter.$or[1].followUpReminderEnabled,true);assert.equal(r.filter.$or[1].response.$ne,'declined');assert.equal(r.res.body.data.handledBy,'actor');assert.equal((await handle('superadmin',{exists:false})).res.code,409);assert.equal((await handle('familyDoctor',{note:' '})).res.code,400)});
const sectionStart=src.indexOf('    // Read-only projection: customer interest');const sectionEnd=src.indexOf('    // 统一归属闸门',sectionStart);
test('actual workbench projection restricts roles and customer scope without writing',async()=>{for(const role of ['familyDoctor','superadmin','healthManager','healthPlanner','nutritionist']){let reads=0,filter;const todos=[];const source={...row,plannedFollowUpDate:'2000-01-01'};await vm.runInNewContext('(async()=>{'+src.slice(sectionStart,sectionEnd)+'})()',{isSuper:role==='superadmin',role,myPatientIds:role==='superadmin'?null:['p'],todos,require:()=>policy,AnnualServiceRecommendation:{find:f=>{reads++;filter=f;return {sort(){return this},populate(){return this},lean:async()=>[source]}}}});const expected=['familyDoctor','superadmin'].includes(role);assert.equal(reads,expected?1:0);assert.equal(todos.length,expected?1:0);if(role==='familyDoctor')assert.equal(filter.patientId.$in[0],'p');if(expected)assert.equal(todos[0].id,'annual_service_interest_r')}});
