const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {sourceIds,findReportArchive}=require('../../shared/diseaseReportArchive.cjs');
test('actual archived relation wins, multiple sources resolve, titles/dates never imply a link',()=>{
 const records=[{_id:'d',name:'专病',courseEntries:[{_id:'e',sourceReportId:'r1',sourceReportIds:['r2','r1'],content:'原文'}]}];
 assert.deepEqual(sourceIds(records[0].courseEntries[0]),['r1','r2']);assert.equal(findReportArchive(records,'r2').entry.content,'原文');assert.equal(findReportArchive(records,'unknown'),null);
});
async function link({role='familyDoctor',scope=['p'],foreign=false,match=1,existing=false}={}){
 const patient={_id:'p',diseaseRecords:[{_id:'d',name:'专病',courseEntries:[{_id:'e',content:'历史手工原文',verificationStatus:'source_verified',...(existing?{sourceReportId:'r'}:{})}]}]};let handler,written;
 const mocks={express:{Router:()=>({post:(p,...f)=>handler=f.at(-1)})},'../middleware/staffAuth':()=>{},'../models/User':{findById:()=>({select:()=>({lean:async()=>patient})}),collection:{updateOne:async(q,u)=>{written={q,u};return{matchedCount:match}}}},'../models/MedicalReport':{findOne:q=>{assert.equal(q.user,'p');assert.equal(q.audit_status,'audited');return{select:()=>({lean:async()=>foreign?null:{_id:'r',title:'病历'}})}}},'../../../shared/diseaseReportArchive.cjs':{sourceIds,findReportArchive}};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../src/routes/diseaseReportLinks'),'utf8'),{module,require:n=>mocks[n]});module.exports({getVisiblePlanPatientIds:async()=>scope});const res={code:200,status(c){this.code=c;return this},json(b){this.body=b}};await handler({params:{id:'p',recordId:'d'},staff:{role,_id:'s',name:'顾问'},body:{reportId:'r',entryId:'e'}},res);return{res,written,patient};
}
test('explicit historical source association keeps original clinical content and adds no new entry',async()=>{const {res,written,patient}=await link();assert.equal(res.code,200);const entries=written.u.$set.diseaseRecords[0].courseEntries;assert.equal(entries.length,1);assert.equal(entries[0].content,'历史手工原文');assert.equal(entries[0].sourceReportIds[0],'r');assert.equal(entries[0].sourceLinkHistory[0].linkedBy,'s');assert.equal(written.q.diseaseRecords,patient.diseaseRecords);const retry=await link({existing:true});assert.equal(retry.res.body.unchanged,true);assert.equal(retry.written,undefined)});
test('source linking enforces reviewer role, membership, reviewed source and concurrent version',async()=>{for(const [o,c] of [[{role:'nurse'},403],[{scope:[]},403],[{foreign:true},404],[{match:0},409]])assert.equal((await link(o)).res.code,c)});
test('existing archive prevents AI regeneration even when report draft status is missing',async()=>{
 const source=fs.readFileSync(require.resolve('../src/routes/staff'),'utf8');const a=source.indexOf("router.post('/medical-reports/:id/health-course-draft'");const b=source.indexOf("router.put('/medical-reports/:id/health-course-draft'",a);let handler,generated=false;
 vm.runInNewContext(source.slice(a,b),{router:{post:(p,...f)=>handler=f.at(-1)},staffAuth:()=>{},getVisiblePlanPatientIds:async()=>['p'],MedicalReport:{findById:async()=>({_id:'r',user:'p',documentCategory:'exam_report',audit_status:'audited'})},User:{findById:()=>({select:()=>({lean:async()=>({diseaseRecords:[{_id:'d',name:'专病',courseEntries:[{sourceReportId:'r',content:'已归档'}]}]})})})},normalizedDiseaseRecords:p=>p.diseaseRecords,findReportArchive,HEALTH_COURSE_DOCUMENTS:new Set(['exam_report']),generateHealthCourseDraft:async()=>{generated=true}});
 const res={status(){return this},json(b){this.body=b}};await handler({params:{id:'r'},staff:{role:'familyDoctor'},body:{}},res);assert.equal(res.body.data.alreadyArchived,true);assert.equal(generated,false);
});
