const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../src/routes/staff'),'utf8');
const start=source.indexOf("router.put('/medical-reports/:id/health-course-draft'");const end=source.indexOf('// DELETE /api/staff/medical-reports/',start);
async function run({scope=['p'],date='2026-09-10',match=1,action='approve',sourceChanged=false}={}){
 let handler,write,saved=false;const report={_id:'r',user:'p',audit_status:'audited',healthCourseDraft:{status:'pending_review',content:'AI草稿',sourceVersion:'v'},save:async()=>{saved=true}};
 const patient={_id:'p',diseaseRecords:[{_id:'d',name:'测试',courseEntries:[]}]};
 vm.runInNewContext(source.slice(start,end),{router:{put:(p,...f)=>handler=f.at(-1)},staffAuth:()=>{},getVisiblePlanPatientIds:async()=>scope,MedicalReport:{findById:async()=>report},User:{findById:()=>({select:()=>({lean:async()=>patient})}),collection:{updateOne:async(q,u)=>{write={q,u};return{matchedCount:match}}}},normalizedDiseaseRecords:p=>structuredClone(p.diseaseRecords),cleanMedicalText:v=>String(v||''),mergedHealthChange:b=>b.content,recordVersion:()=>sourceChanged?'changed':'v',courseEvidence:r=>r,mongoose:{Types:{ObjectId:function(){return 'e'}}}});
 const res={code:200,status(c){this.code=c;return this},json(b){this.body=b}};await handler({params:{id:'r'},staff:{role:'familyDoctor',_id:'s',name:'顾问'},body:{action,occurredAt:date,diseaseName:'测试',content:'已核对内容'}},res);return{res,write,saved,patient};
}
test('AI timeline approval uses confirmed visit date and preserves source and reviewer with CAS',async()=>{const {res,write,patient}=await run();assert.equal(res.code,200);const e=write.u.$set.diseaseRecords[0].courseEntries[0];assert.equal(e.occurredAt.toISOString(),'2026-09-09T16:00:00.000Z');assert.equal(e.sourceReportId,'r');assert.equal(e.reviewedById,'s');assert.equal(write.q.diseaseRecords,patient.diseaseRecords)});
test('missing dates, foreign patients, changed evidence and concurrent updates cannot archive',async()=>{for(const [options,code] of [[{date:''},400],[{scope:[]},403],[{sourceChanged:true},409],[{match:0},409]]){const result=await run(options);assert.equal(result.res.code,code);assert.equal(result.saved,false)}});
