const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '../src/routes/staff.js'), 'utf8')

test('service tasks use the native ownership query before server-side filtering', () => {
  const route = source.match(/router\.get\('\/service-tasks'[\s\S]*?res\.json\(\{ success: true, data: tasks\.map/)
  assert.ok(route, 'service-tasks route should exist')
  assert.match(route[0], /const staffId = String\(req\.staff\._id\)/)
  assert.match(route[0], /assignedTo: \{ \$in: \[req\.staff\._id, staffId\] \}/)
  assert.match(route[0], /FollowUp\.collection\.find\(filter\)/)
  assert.match(route[0], /rawTasks\.map\(task => FollowUp\.hydrate\(task\)\)/)
  assert.match(route[0], /await FollowUp\.populate\(queriedTasks/)
  assert.doesNotMatch(route[0], /FollowUp\.find\(filter\)/)
  assert.match(route[0], /const isServiceTask = \(task\.sourceType === 'health_plan'/)
  assert.match(route[0], /!\['planned', 'in_progress', 'missed'\]\.includes\(task\.status\)/)
  assert.doesNotMatch(route[0], /status.*\$in.*planned.*in_progress.*missed/)
})
