const test=require('node:test'),assert=require('node:assert/strict');
const {buildFixture}=require('./helpers/serviceGroupFixture');
const crypto=require('crypto');
test('自动收件：纯图片、逐份确认、权限、重复及失败恢复',async t=>{
 const f=buildFixture(),s=f.app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));t.after(()=>s.close());
 const base=`http://127.0.0.1:${s.address().port}`,g=f.models.ServiceGroup.rows[0];g.archiveConsent=true;g.chatId='test-inbox';
 Object.assign(process.env,{SERVICE_GROUP_ARCHIVE_ENABLED:'true',SERVICE_GROUP_BRIDGE_SECRET:'synthetic',SERVICE_GROUP_MESSAGE_KEY:'ab'.repeat(32),SERVICE_GROUP_BRIDGE_TENANT_ID:f.ids.tenant});
 t.after(()=>['SERVICE_GROUP_ARCHIVE_ENABLED','SERVICE_GROUP_BRIDGE_SECRET','SERVICE_GROUP_MESSAGE_KEY','SERVICE_GROUP_BRIDGE_TENANT_ID'].forEach(k=>delete process.env[k]));
 const req=async(path,body,other=false)=>{const r=await fetch(base+'/api/staff/service-groups/'+f.ids.group+path,{method:body?'POST':'GET',headers:{authorization:'test','content-type':'application/json',...(other?{'x-test-other':'true'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,...await r.json()};};
 const ingest=async(id,bytes)=>{const raw=JSON.stringify({chatId:g.chatId,messageId:id,sender:'synthetic sender',sentAt:new Date().toISOString(),consent:true,text:'',file:{name:id+'.png',base64:bytes.toString('base64')}}),ts=String(Date.now());
 const r=await fetch(base+'/api/integrations/service-groups/messages',{method:'POST',headers:{'content-type':'application/json','x-jy-timestamp':ts,'x-jy-signature':crypto.createHmac('sha256','synthetic').update(`${ts}.${raw}`).digest('hex')},body:raw});assert.equal(r.status,200);};
 const png=Buffer.from('89504e470d0a1a0a0000000d49484452','hex');
 await ingest('a',png);await ingest('a',png);await ingest('b',Buffer.concat([png,Buffer.from('b')]));
 assert.equal(f.models.ServiceGroupMessage.rows.length,2);assert.equal(f.models.MedicalReport.rows.length,0,'收件不入正式报告');
 assert.equal((await req('/inbox',undefined,true)).status,403);
 const inbox=(await req('/inbox')).data;assert.equal(inbox.length,2);assert.ok(inbox[0].previewUrl);assert.equal(inbox[0].attachment,undefined);
 const ids=inbox.map(m=>m._id),payload={messageIds:ids,patientId:f.ids.patient,purpose:'report',title:'就诊资料',date:'2026-09-09',documentCategory:'outpatient_record'};
 assert.equal((await req('/inbox/confirm',{...payload,patientId:f.ids.outsider})).status,400);
 const results=await req('/inbox/confirm',payload);assert.ok(results.data.every(r=>r.success));assert.equal(f.models.MedicalReport.rows.length,2);
 assert.ok(f.models.MedicalReport.rows.every(r=>r.aiStatus==='none'&&r.audit_status==='unaudited'));
 assert.ok((await req('/inbox/confirm',payload)).data.every(r=>r.duplicate));assert.equal(f.models.MedicalReport.rows.length,2);
 assert.ok((await req('/inbox/confirm',{...payload,purpose:'checkin'})).data.every(r=>!r.success),'已归档不能改用途');
 assert.ok((await req('/inbox')).data.every(r=>r.state==='archived'));
 assert.equal((await req('/archive-message',{messageId:ids[0],patientId:f.ids.patient,title:'legacy',documentCategory:'outpatient_record'})).status,409);
 const partial=await req('/inbox/confirm',{...payload,messageIds:[ids[0],'000000000000000000000099']});
 assert.equal(partial.data[0].success,true);assert.equal(partial.data[1].success,false);
 await ingest('c',Buffer.concat([png,Buffer.from('c')]));
 const c=f.models.ServiceGroupMessage.rows.find(m=>m.messageId==='c');
 const check={...payload,messageIds:[String(c._id)],purpose:'checkin'};
 const oss=require('../src/utils/oss'),original=oss.getObjectStream;
 oss.getObjectStream=async()=>{throw new Error('synthetic interruption');};
 assert.equal((await req('/inbox/confirm',check)).data[0].success,false);
 oss.getObjectStream=original;
 assert.equal((await req('/inbox/confirm',check)).data[0].success,true);
 assert.equal(f.models.ServiceRecord.rows.length,1);assert.equal(f.models.ServiceRecord.rows[0].attachments.length,1);
 g.archiveConsent=false;assert.deepEqual((await req('/inbox')).data,[]);assert.equal((await req('/inbox/confirm',check)).status,403);
});
