const {buildSync}=require('esbuild');
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const source=`import React from 'react';import {createRoot} from 'react-dom/client';import DateField from './shared/DateField.jsx';function App(){const [d,s]=React.useState('');const [t,u]=React.useState('');return <form style={{width:300}}><label>建议就医/检查日期<DateField type="date" name="visit" aria-label="日期" value={d} onChange={e=>s(e.target.value)} min="2026-01-01" max="2026-12-31" style={{padding:8,border:'1px solid #ddd'}} /></label><label>预约时间<DateField type="datetime-local" aria-label="时间" value={t} onChange={e=>u(e.target.value)} /></label><output>{d+'|'+t}</output></form>}createRoot(document.getElementById('root')).render(<App/>);`;
const js=buildSync({stdin:{contents:source,resolveDir:process.cwd(),loader:'jsx'},bundle:true,write:false,format:'iife',define:{'process.env.NODE_ENV':'"production"'}}).outputFiles[0].text;
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:360,height:400}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<html lang="zh"><meta charset="utf-8"><div id="root"></div></html>');await page.addScriptTag({content:js});const date=page.getByRole('textbox',{name:'日期',exact:true});await date.pressSequentially('20261001');assert.equal(await date.inputValue(),'2026-10-01');await date.fill('2026-10-1');await date.press('0');assert.equal(await date.inputValue(),'2026-10-10');await page.locator('input[type=date]').fill('2026-11-03');assert.equal(await date.inputValue(),'2026-11-03');await date.fill('2027-01-01');assert.equal(await date.evaluate(e=>e.checkValidity()),false);await date.fill('20261001');await date.press('Tab');assert.equal(await date.inputValue(),'2026-10-01');const time=page.getByRole('textbox',{name:'时间',exact:true});await time.fill('2026-10-01 12:30');await time.press('Tab');assert.equal(await time.inputValue(),'2026-10-01T12:30');await page.locator('input[type="datetime-local"]').fill('2026-10-02T13:45');assert.equal(await time.inputValue(),'2026-10-02T13:45');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=360),true);assert.deepEqual(errors,[]);await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'jiayicare-global-date-check.png')});await browser.close();console.log('Browser typing, calendar, min/max, date-time and narrow layout passed');})().catch(e=>{console.error(e);process.exitCode=1});


