const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm'), path = require('node:path');
const {transformSync}=require('esbuild'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<body></body>',{url:'http://localhost',pretendToBeVisual:true}); global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{createRoot}=require('react-dom/client'),act=React.act||require('react-dom/test-utils').act;
function load(file,mocks){const mod={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(path.join(__dirname,'../src',file),'utf8'),{loader:'jsx',format:'cjs'}).code,{module:mod,exports:mod.exports,require:n=>n in mocks?mocks[n]:require(n),window,document,console,Event:window.Event});return mod.exports.default;}
async function mount(C){const el=document.createElement('div');document.body.append(el);const root=createRoot(el);await act(async()=>root.render(React.createElement(C)));return {el,render:async()=>act(async()=>root.render(React.createElement(C))),close:async()=>{await act(async()=>root.unmount());el.remove()}};}
const router={useNavigate:()=>()=>{}};
for(const role of ['healthPlanner','healthManager','familyDoctor','nutritionist'])test(`${role}: empty service queue keeps history; new tasks and errors remain visible`,async()=>{
 let tasks=[],reject=false;
 const C=load('components/ServiceTasksPanel.jsx',{'react-router-dom':router,'../api':{staffAPI:{getServiceTasks:async()=>{if(reject)throw Error('test load failure');return {data:tasks}}}},'../App':{useStaff:()=>({staff:{role}})},'../utils/date':{formatChineseDate:()=>'',formatChineseDateTime:()=>''},'../utils/checkupTaskRouting':{isCheckupDesignStage:()=>false},'./AnnualDispatchCard':()=>null,'../../../shared/annualDispatch.cjs':{dedicated:()=>false},'../utils/serviceTaskTitle.mjs':{serviceTaskTitle:t=>t.theme},'../utils/plannerOrderProgress.mjs':{isCustomerOrder:()=>false,serviceTaskGroupKey:t=>t._id}});
 const h=await mount(C);try{assert.ok(h.el.querySelector('.workbench-compact'));assert.match(h.el.textContent,/查看已处理/);tasks=[{_id:'synthetic',theme:'合成服务事项',taskRole:'executor',status:'planned',date:new Date().toISOString(),patientId:{_id:'p',name:'示例会员'}}];await act(async()=>window.dispatchEvent(new window.Event('focus')));assert.match(h.el.textContent,/合成服务事项/);assert.equal(h.el.querySelector('.workbench-compact'),null);reject=true;await act(async()=>window.dispatchEvent(new window.Event('focus')));assert.match(h.el.querySelector('[role=alert]').textContent,/test load failure/);assert.match(h.el.textContent,/合成服务事项/);}finally{await h.close()}
});
test('consultation empty state retains navigation and expands for new work',async()=>{let items=[];const C=load('components/ConsultationTodosPanel.jsx',{'react-router-dom':router,'../api':{staffAPI:{getConsultationTodos:async()=>({data:items})}}});const h=await mount(C);try{assert.ok(h.el.querySelector('.workbench-compact'));assert.match(h.el.textContent,/全部咨询/);items=[{id:'x',label:'待联系',name:'示例',summary:'服务咨询',link:'/visitor-leads',kind:'lead'}];await act(async()=>window.dispatchEvent(new window.Event('focus')));assert.match(h.el.textContent,/服务咨询/);assert.equal(h.el.querySelector('.workbench-compact'),null)}finally{await h.close()}});
test('history-only shipments expand and collapse without losing the entry',async()=>{const C=load('components/OrderShipmentsPanel.jsx',{'react-router-dom':router,'../api':{staffAPI:{},getToken:()=>''},'../App':{useStaff:()=>({staff:{role:'healthManager'}})},'../hooks/useWorkbenchResource':(_,key)=>({loading:false,error:'',data:key.includes('shipment-history')?{total:1,totalPages:1,items:[{_id:'h',user:{name:'示例客户'},serviceName:'历史商品',fulfillment:{trackingNo:'sample'}}]}:[]}), './Pagination':()=>null,'./OrderShipmentsPanel.css':{}});const h=await mount(C);try{assert.ok(h.el.querySelector('.workbench-compact'));await act(async()=>h.el.querySelector('button').click());assert.match(h.el.textContent,/历史商品/);const btn=[...h.el.querySelectorAll('button')].find(x=>x.textContent.includes('收起已处理'));await act(async()=>btn.click());assert.ok(h.el.querySelector('.workbench-compact'))}finally{await h.close()}});

test('follow-up empty compact state never hides waiting service progress or errors',async()=>{let data={followUps:[],total:0,workbenchSummary:{counts:{},waiting:0}},error='';const C=load('components/FollowUpsPanel.jsx',{'react-router-dom':router,'../api':{staffAPI:{},getToken:()=>''},'../utils/date':{formatChineseDate:()=>''},'./Pagination':()=>null,'../hooks/useWorkbenchResource':()=>({data,loading:false,error,refresh:()=>{}})});const h=await mount(C);try{assert.ok(h.el.querySelector('.workbench-compact'));data={...data,workbenchSummary:{counts:{},waiting:2}};await h.render();assert.equal(h.el.querySelector('.workbench-compact'),null);assert.match(h.el.textContent,/服务进行中 2/);error='offline';await h.render();assert.match(h.el.querySelector('[role=alert]').textContent,/offline/)}finally{await h.close()}});
