import React, { useEffect, useState } from 'react'
import { staffAPI } from '../api'
import archiveHelpers from '../../../shared/diseaseReportArchive.cjs'
export function ArchivedDiagnosis({ archive, onClose }) {
  const e=archive.entry
  return <div className="modal-overlay" onClick={onClose}><div className="modal" style={{maxWidth:760}} onClick={event=>event.stopPropagation()}><div className="modal-header"><h3>已归档诊疗记录 · {archive.diseaseName}</h3><button className="modal-close" onClick={onClose}>×</button></div><div className="modal-body"><p style={{color:'#1e6b50'}}>此记录已归档，查看无需再次审核。</p><p>{e.occurredAt ? new Date(e.occurredAt).toLocaleDateString('zh-CN'):'日期未记录'} · {e.sourceInstitution || '来源机构未记录'}</p>{[['诊疗情况',e.content || e.symptoms],['检查',e.examination],['诊断',e.diagnosis],['用药',e.medicationChange],['反馈',e.treatmentResponse],['后续安排',e.nextPlan]].map(([k,v])=>v&&<div key={k} style={{marginTop:14,whiteSpace:'pre-wrap',lineHeight:1.8}}><b>{k}：</b>{v}</div>)}</div><div className="modal-footer"><button className="btn btn-secondary" onClick={onClose}>关闭</button></div></div></div>
}
export default function DiseaseReportPicker({ patientId, dossier, records, onClose, onUpload, onReview, onViewSource, onSaved, canReview }) {
  const [reports,setReports]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[filter,setFilter]=useState('unarchived'),[archive,setArchive]=useState(null),[linking,setLinking]=useState(null),[entryId,setEntryId]=useState(''),[saving,setSaving]=useState(false),[localLinks,setLocalLinks]=useState({})
  const load=async()=>{setLoading(true);setError('');try{const r=await staffAPI.getPatientReports(patientId);setReports(r.data || [])}catch(e){setError(e.message || '资料加载失败')}finally{setLoading(false)}}
  useEffect(()=>{load()},[patientId])
  const getArchive=r=>localLinks[r._id] || archiveHelpers.findReportArchive(records,r._id)
  const eligible=reports.filter(r=>['outpatient_record','inpatient_record','exam_report','lab_report'].includes(r.documentCategory))
  const filtered=eligible.filter(r=>filter==='archived'?getArchive(r)?.recordId===String(dossier._id):!getArchive(r))
  const link=async()=>{setSaving(true);setError('');try{const r=await staffAPI.linkDiseaseReport(patientId,dossier._id,{reportId:linking._id,entryId});setLocalLinks(v=>({...v,[linking._id]:r.data.archive}));setLinking(null);setArchive(r.data.archive);await onSaved()}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="modal-overlay" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><div className="modal" style={{maxWidth:980,width:'95vw'}}><div className="modal-header"><div><h3>专病病历 · {dossier.name}</h3><p style={{fontSize:12,color:'#70827b'}}>已归档直接查看；仅新增诊疗内容需要顾问审核。</p></div><button className="modal-close" disabled={saving} onClick={onClose}>×</button></div><div className="modal-body">
    <div className="disease-actions"><button className="btn btn-secondary" onClick={()=>{setFilter('unarchived');setPage(1)}}>待选择病历</button><button className="btn btn-secondary" onClick={()=>{setFilter('archived');setPage(1)}}>本专病已归档</button><button className="btn btn-primary" onClick={onUpload}>上传新病历</button></div>
    <p style={{fontSize:12,color:'#70827b',margin:'12px 0'}}>{filter==='unarchived'?'以下为尚未关联的病历，请核对是否属于当前专病。历史手工记录可只补关联来源，不重复入档。':'展示已有明确病历来源的诊疗记录。历史未关联来源的记录仍保留在时间轴。'}</p>
    {error&&<p role="alert" style={{color:'#b42318'}}>{error}<button onClick={load}>重新加载</button></p>}
    {loading?<p>加载中…</p>:!filtered.length?<p>暂无符合条件的病历。</p>:filtered.slice((page-1)*5,page*5).map(r=>{const a=getArchive(r);return <div key={r._id} style={{padding:'16px 0',borderBottom:'1px solid #e4ece8'}}><strong>{r.title || '医疗资料'}</strong><p style={{fontSize:12,color:'#70827b',margin:'6px 0'}}>{r.hospital || r.institution || '来源机构未记录'} · 原始资料{r.audit_status==='audited'?'已审核':'待审核'} · 专病{a?'已归档':r.healthCourseDraft?.status==='pending_review'?'草稿待审核':r.healthCourseDraft?.status==='approved'?'归档状态待核对':'尚未关联'}</p><div className="disease-actions"><button className="btn btn-secondary btn-sm" onClick={()=>onViewSource(r)}>查看原始病历</button>{a?<button className="btn btn-primary btn-sm" onClick={()=>setArchive(a)}>查看诊疗记录</button>:canReview&&r.audit_status==='audited'&&<><button className="btn btn-primary btn-sm" onClick={()=>onReview(r,{diseaseName:dossier.name})}>{r.healthCourseDraft?.status==='pending_review'?'审核新增诊疗草稿':r.healthCourseDraft?.status==='approved'?'核对归档状态':'AI提取新增诊疗'}</button>{dossier._id&&dossier._id!=='legacy'&&dossier.courseEntries?.length>0&&<button className="btn btn-secondary btn-sm" onClick={()=>{setLinking(r);setEntryId('')}}>关联已有诊疗记录</button>}</>}</div></div>})}
    {filtered.length>5&&<div className="disease-pagination"><button className="btn btn-secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.ceil(filtered.length/5)}</span><button className="btn btn-secondary" disabled={page*5>=filtered.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div>}
    {linking&&<div style={{padding:16,background:'#f3f8f5',marginTop:16}}><b>将「{linking.title}」关联到已有记录</b><p>仅补充来源关系，保留原文，不新增诊疗记录。请先核对原始病历和时间轴。</p><select className="form-control" value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">请选择原诊疗记录</option>{(dossier.courseEntries||[]).filter(e=>e.verificationStatus!=='pending_verification').map(e=><option key={e._id} value={String(e._id)}>{e.occurredAt?new Date(e.occurredAt).toLocaleDateString('zh-CN'):'日期未记录'} · {(e.content || e.symptoms || '').slice(0,80)}</option>)}</select><button className="btn btn-primary" disabled={!entryId||saving} onClick={link}>确认仅关联来源</button><button className="btn btn-secondary" disabled={saving} onClick={()=>setLinking(null)}>取消</button></div>}
  </div></div>{archive&&<ArchivedDiagnosis archive={archive} onClose={()=>setArchive(null)}/>}</div>
}
