import React, { useEffect, useState } from 'react'
import { adminAPI } from '../api'
import { useToast } from '../App'

const SCOPES = [['basic','基本资料'],['healthProfile','健康档案'],['reports','体检报告'],['healthRecords','健康监测'],['medications','用药/营养素'],['followups','随访'],['plans','管理方案'],['aiAnalysis','既有AI分析']]
const blank = () => ({ name: '', status: 'active', content: { templateKey: `specialty_${Date.now()}`, title: '', description: '', target: '研判结论', outputGuide: '', contextScopes: SCOPES.map(v => v[0]), sortOrder: 100 } })

export default function AiCaseReviewTemplatePage() {
  const toast = useToast(); const [items, setItems] = useState([]); const [settings, setSettings] = useState(null)
  const [form, setForm] = useState(blank()); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false)
  const load = async () => { try { const res = await adminAPI.planTemplates('ai_case_review'); const all = res.data || []; setSettings(all.find(v => v.content?.kind === 'settings') || null); setItems(all.filter(v => v.content?.kind !== 'settings').sort((a,b) => (a.content?.sortOrder ?? 999) - (b.content?.sortOrder ?? 999))) } catch (e) { toast(e.message) } }
  useEffect(() => { load() }, [])
  const edit = item => { setEditing(item || null); setForm(item ? { name: item.name, status: item.status, content: { ...blank().content, ...item.content } } : blank()); setOpen(true) }
  const content = (key, value) => setForm(v => ({ ...v, content: { ...v.content, [key]: value } }))
  const save = async () => { if (!form.name.trim() || !form.content.title.trim() || !form.content.description.trim()) return toast('请填写显示名称、默认主题名和问题说明'); setBusy(true); try { const data = { type: 'ai_case_review', ...form }; editing ? await adminAPI.updatePlanTemplate(editing._id, data) : await adminAPI.createPlanTemplate(data); setOpen(false); toast('专项研判主题已保存'); await load() } catch (e) { toast(e.message) } finally { setBusy(false) } }
  const toggle = async item => { try { await adminAPI.togglePlanTemplate(item._id); await load() } catch (e) { toast(e.message) } }
  const setCustom = async allowed => { if (!settings) return; try { await adminAPI.updatePlanTemplate(settings._id, { name: settings.name, status: 'active', content: { ...settings.content, allowCustomTopic: allowed } }); await load(); toast('自定义主题设置已保存') } catch (e) { toast(e.message) } }
  return <div><div className="page-header"><div><div className="page-title">专项研判设置</div><div className="page-subtitle">统一管理医护端“专项研判 → 新建主题”的主题库；阶段评估不在这里配置。</div></div><button className="btn btn-primary" onClick={() => edit(null)}>新增研判主题</button></div>
    <div className="card" style={{ marginBottom: 16 }}><div className="card-body" style={{ display:'flex',justifyContent:'space-between',alignItems:'center' }}><div><strong>允许医护自定义主题</strong><div style={{ color:'#65776F',fontSize:12,marginTop:4 }}>关闭后只能选择 Admin 已启用的主题，便于统一研判口径。</div></div><input type="checkbox" checked={settings?.content?.allowCustomTopic !== false} disabled={!settings} onChange={e => setCustom(e.target.checked)} /></div></div>
    <div className="card"><div className="card-body">{items.map(item => <div key={item._id} style={{ border:'1px solid #E0E8E3',borderRadius:10,padding:14,marginBottom:10,display:'flex',justifyContent:'space-between',gap:16 }}><div><div style={{ fontWeight:800 }}>{item.name}<span style={{ fontSize:12,color:item.status === 'active' ? '#16845B':'#8AA89C',marginLeft:8 }}>{item.status === 'active' ? '已启用':'已停用'}</span></div><div style={{ fontSize:13,marginTop:5 }}>默认主题：{item.content?.title || item.name}</div><div style={{ color:'#65776F',fontSize:12,marginTop:4 }}>{item.content?.description}</div><div style={{ color:'#8AA89C',fontSize:12,marginTop:4 }}>排序 {item.content?.sortOrder ?? 999} · 确认后用于：{item.content?.target || '研判结论'}</div></div><div style={{ display:'flex',gap:8,alignItems:'center' }}><button className="btn btn-secondary btn-sm" onClick={() => edit(item)}>编辑</button><button className="btn btn-secondary btn-sm" onClick={() => toggle(item)}>{item.status === 'active' ? '停用':'启用'}</button></div></div>)}</div></div>
    {open && <div className="modal-overlay"><div className="modal" style={{ maxWidth:720 }}><div className="modal-header"><div className="modal-title">{editing ? '编辑':'新增'}研判主题</div><button className="modal-close" onClick={() => setOpen(false)}>×</button></div><div className="modal-body">
      <div className="form-group"><label className="form-label">下拉显示名称</label><input className="form-input" value={form.name} onChange={e => setForm(v => ({...v,name:e.target.value}))} placeholder="如：甲状腺专病分析" /></div><div className="form-group"><label className="form-label">默认主题名称</label><input className="form-input" value={form.content.title} onChange={e => content('title',e.target.value)} /></div><div className="form-group"><label className="form-label">默认问题说明</label><textarea className="form-input" rows={3} value={form.content.description} onChange={e => content('description',e.target.value)} /></div><div className="form-group"><label className="form-label">固定输出结构</label><textarea className="form-input" rows={3} value={form.content.outputGuide} onChange={e => content('outputGuide',e.target.value)} /></div>
      <div style={{ display:'grid',gridTemplateColumns:'1fr 120px',gap:12 }}><div className="form-group"><label className="form-label">确认后用途</label><input className="form-input" value={form.content.target} onChange={e => content('target',e.target.value)} /></div><div className="form-group"><label className="form-label">显示排序</label><input className="form-input" type="number" value={form.content.sortOrder} onChange={e => content('sortOrder',Number(e.target.value))} /></div></div><div className="form-group"><label className="form-label">默认调取资料</label><div style={{ display:'flex',flexWrap:'wrap',gap:10 }}>{SCOPES.map(([key,label]) => <label key={key}><input type="checkbox" checked={form.content.contextScopes.includes(key)} onChange={() => content('contextScopes',form.content.contextScopes.includes(key) ? form.content.contextScopes.filter(v=>v!==key) : [...form.content.contextScopes,key])} /> {label}</label>)}</div></div>
    </div><div className="modal-footer"><button className="btn btn-secondary" onClick={() => setOpen(false)}>取消</button><button className="btn btn-primary" disabled={busy} onClick={save}>保存</button></div></div></div>}</div>
}
