import React,{useEffect,useState} from 'react'
import {adminAPI} from '../api'
import config from '../../../shared/careFlow.cjs'
export default function CareQualityPage(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[improvement,setImprovement]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false)
  const load=()=>adminAPI.getCareQuality().then(r=>setData(r.data)).catch(e=>setError(e.message))
  useEffect(()=>{load()},[])
  return <div style={{padding:24}}><h2>就医协助质量与回退留痕</h2><p>仅统计接入新流程后的记录；接收回退不等于人员过错。责任归因由管理员复核，优化意见只追加，不修改原记录或自动变更医疗规则。</p>{error&&<p role="alert">{error}</p>}{data&&<>
    <p>已纳入 {data.flows} 项服务 · 回退 {data.returns} 次{data.limited?'（仅最近更新500项；不是全量统计）':''}</p>
    <table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['责任环节','接收人员','问题分类','回退次数','涉及服务','重复回退','平均修订耗时'].map(t=><th key={t} style={{textAlign:'left',padding:10}}>{t}</th>)}</tr></thead><tbody>{data.groups.map((g,i)=><tr key={i}><td>{config.labels[g.stage]}</td><td>{g.person}</td><td>{config.categories[g.category]}</td><td>{g.count}</td><td>{g.cases}</td><td>{g.repeatCount}</td><td>{g.averageHours===null?'尚未返回':`${g.averageHours}小时`}</td></tr>)}</tbody></table>
    <h3>回退明细与改进复核</h3>{data.rows.map((r,i)=><section key={i} style={{border:'1px solid #ddd',padding:16,marginTop:12}}><b>{r.title} · {config.labels[r.stage]} → {config.labels[r.targetStage]}</b><p>{r.name} → {r.targetName} · {new Date(r.at).toLocaleString('zh-CN')}</p><p>{config.categories[r.category]}：{r.reason}</p><p>{r.correction?`已修订直返：${r.correction.correction}`:'尚待修订返回'}</p><details><summary>修订前后内容</summary><pre style={{whiteSpace:'pre-wrap',wordBreak:'break-word'}}>{JSON.stringify({修订前:r.before,修订后:r.correction?.after},null,2)}</pre></details>{r.reviews.map((v,j)=><p key={j}>复核：{v.note}；优化措施：{v.improvement}；{v.personnelIssueConfirmed?'已复核存在人员问题':'未认定为人员过错'} · {v.name} · {new Date(v.at).toLocaleString('zh-CN')}</p>)}<button onClick={()=>{setError('');setSelected(r);setNote('');setImprovement('');setConfirmed(false)}}>追加归因与优化措施</button></section>)}
  </>}{selected&&<div style={{position:'fixed',inset:0,background:'#0005',display:'grid',placeItems:'center'}}><section style={{background:'white',padding:24,width:'min(600px,90vw)',display:'grid',gap:12}}><h3>追加质量复核</h3>{error&&<p role="alert" style={{color:"#B91C1C"}}>{error}</p>}<textarea placeholder="核实情况及原因" value={note} onChange={e=>setNote(e.target.value)} maxLength={3000}/><textarea placeholder="优化措施，如交接校验、表单完善或培训；不自动修改规则" value={improvement} onChange={e=>setImprovement(e.target.value)} maxLength={3000}/><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 经复核确认存在人员处理问题（非默认认定）</label><button disabled={busy||!note.trim()||!improvement.trim()} onClick={async()=>{setBusy(true);try{await adminAPI.reviewCareQuality(selected.flowId,{token:selected.token,note,improvement,personnelIssueConfirmed:confirmed});setSelected(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>追加保存</button><button onClick={()=>setSelected(null)}>取消</button></section></div>}</div>
}
