const test=require('node:test'),assert=require('node:assert/strict');
const mongoose=require('mongoose'),express=require('express'),jwt=require('jsonwebtoken');
const {randomUUID}=require('crypto');
test('two synthetic clients: questionnaire read, draft, resume, verified archive and completion over authenticated HTTP', {timeout:45000},async t=>{
 const name=`jiayicare_lifestyle_test_${randomUUID().replaceAll('-','')}`;
 await mongoose.connect(`mongodb://127.0.0.1:27981/${name}`,{serverSelectionTimeoutMS:3000,autoIndex:false});
 const oldSecret=process.env.JWT_SECRET;process.env.JWT_SECRET=randomUUID();
 t.after(async()=>{assert.equal(mongoose.connection.name,name);await mongoose.connection.dropDatabase();await mongoose.disconnect();if(oldSecret===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=oldSecret});
 const User=require('../../src/models/User'),Admin=require('../../src/models/Admin'),FollowUp=require('../../src/models/FollowUp');
 const {DynamicQuestionnaire,QuestionnaireResponse}=require('../../src/models/DynamicQuestionnaire');
 const impl=require('../../src/utils/lifestyleInterview'),{effectiveLifestyle}=require('../../src/utils/effectiveLifestyle');
 const id=()=>new mongoose.Types.ObjectId(),ns=id(),outsider=id(),qid=new mongoose.Types.ObjectId('6a49eab9fc1595013da70645');
 await Admin.collection.insertMany([{_id:ns,username:'synthetic_nutrition',role:'nutritionist',name:'测试营养师'},{_id:outsider,username:'synthetic_other',role:'nutritionist'}]);
 await DynamicQuestionnaire.collection.insertOne({_id:qid,title:'隔离生活方式测试问卷',updatedAt:new Date(),questions:[{id:'breakfast',text:'早餐时间',type:'text',archiveField:'lifestyle_data.breakfastTime'},{id:'lunch',text:'午餐时间',type:'text',archiveField:'lifestyle_data.lunchTime'}]});
 const app=express();app.use(express.json());app.use(require('../../src/middleware/staffAuth'));app.post('/patients/:id/start',impl.start);app.get('/followups/:id',impl.handle);app.post('/followups/:id',impl.handle);
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));
 const token=actor=>jwt.sign({type:'admin',id:String(actor)},process.env.JWT_SECRET);
 const call=async(path,body,actor=ns)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token(actor)}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,...await r.json()}};
 for(const answered of [true,false])await t.test(answered?'已填问卷：带入→核实修正→保留原答卷':'未填问卷：空白→代填→写入基础档案',async()=>{
  const patient=id();await User.collection.insertOne({_id:patient,name:answered?'测试客户A-已填':'测试客户B-未填',assignedNutritionist:ns,lifestyle_data:answered?{breakfastTime:'07:00'}:{},lifestyleHistory:[]});
  const original=id();if(answered)await QuestionnaireResponse.collection.insertOne({_id:original,user:patient,questionnaire:qid,answers:{breakfast:'07:30',lunch:'12:00'},submittedAt:new Date()});
  const start=await call(`/patients/${patient}/start`,{});assert.equal(start.status,200,JSON.stringify(start));const task=start.data;
  assert.equal((await call(`/patients/${patient}/start`,{})).data._id,task._id);
  assert.equal((await call(`/followups/${task._id}`,undefined,outsider)).status,403);
  let view=(await call(`/followups/${task._id}`)).data;
  assert.equal(view.initialAnswers.breakfast,answered?'07:30':undefined);assert.equal(Boolean(view.sourceResponseId),answered);
  const before=JSON.stringify(await User.findById(patient).lean());
  const body={action:'draft',answers:{...view.initialAnswers,breakfast:'08:00',lunch:'12:30'},confirmed:['breakfast'],notes:'合成测试：午餐尚未核实',method:'电话访谈',baseUpdatedAt:view.task.updatedAt,patientVersion:view.patientVersion,templateVersion:view.template.updatedAt};
  const draft=await call(`/followups/${task._id}`,body);assert.equal(draft.status,200,JSON.stringify(draft));
  assert.equal(JSON.stringify(await User.findById(patient).lean()),before);
  assert.equal(await QuestionnaireResponse.countDocuments({user:patient}),answered?1:0);
  view=(await call(`/followups/${task._id}`)).data;assert.equal(view.task.formData.lifestyleInterview.answers.breakfast,'08:00');assert.equal(view.task.formData.lifestyleInterview.notes,body.notes);
  const submit={...body,action:'submit',baseUpdatedAt:view.task.updatedAt};
  if(answered)assert.equal((await call(`/followups/${task._id}`,submit)).status,400);
  const saved=await call(`/followups/${task._id}`,{...submit,confirmConflicts:true});assert.equal(saved.status,200,JSON.stringify(saved));assert.equal(saved.data.status,'completed');assert.equal(saved.data.reviewAssignedTo,null);
  const user=await User.findById(patient).lean();assert.equal(effectiveLifestyle(user).breakfastTime,'08:00');assert.equal(user.lifestyle_data.breakfastTime,answered?'07:00':'08:00');assert.equal(effectiveLifestyle(user).lunchTime,undefined);assert.equal(user.lifestyleHistory.length,1);
  const response=await QuestionnaireResponse.findOne({user:patient,proxyEntry:{$exists:true}}).lean();assert.deepEqual(response.answers,{breakfast:'08:00'});assert.equal(String(response.proxyEntry.sourceFollowUpId),task._id);assert.ok(response.proxyEntry.pendingQuestionIds.includes('lunch'));
  if(answered)assert.deepEqual((await QuestionnaireResponse.findById(original).lean()).answers,{breakfast:'07:30',lunch:'12:00'});
  assert.equal((await call(`/followups/${task._id}`,{...submit,confirmConflicts:true})).status,409);assert.equal(await FollowUp.countDocuments({patientId:patient}),1);assert.equal(await QuestionnaireResponse.countDocuments({user:patient}),answered?2:1);
 });
});
