const fs = require('fs'), path = require('path'), assert = require('assert/strict'), m = require('mongoose');
(async () => {
  const file = process.argv[2], s = JSON.parse(fs.readFileSync(file)), evidenceFile = path.join(path.dirname(file), 'live-ai-evidence.json');
  assert.equal(s.api, 'http://127.0.0.1:3002/api'); assert.match(s.database, /^jiayicare_acceptance_[a-f0-9]{32}$/);
  const evidence = JSON.parse(fs.readFileSync(evidenceFile));
  await m.connect('mongodb://127.0.0.1:27134/' + s.database, { autoIndex: false, autoCreate: false });
  const User = require('../../src/models/User'), Template = require('../../src/models/PlanTemplate');
  assert.equal((await User.findById(s.patientId)).name, '隔离验收客户（纯虚构）');
  let token;
  const api = async (route, method, body, expected = 200) => {
    const r = await fetch(s.api + route, { method, headers: { 'content-type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(110000) });
    const data = await r.json(); assert.equal(r.status, expected, data.message); return data;
  };
  const login = async role => { const a = s.accounts.find(a => a.role === role); token = (await api('/staff/login','POST',{ username:a.username,password:a.password })).data.token; };
  const year = new Date().getFullYear(), templateId = evidence.annual.template._id;
  await User.updateOne({ _id: s.patientId }, { $set: { clientBrand: 'jiayiguanjia' } });
  await Template.updateOne({ _id: templateId }, { $set: { 'content.servicePlanCode': 'jygj_prevention' } });
  await login('healthManager');
  await api(`/staff/patients/${s.patientId}/ai-annual-plan`, 'POST', { year }, 403);
  await login('familyDoctor');
  const annual = await api(`/staff/patients/${s.patientId}/ai-annual-plan`, 'POST', { year, planType: 'jygj_prevention', templateId, notes: '纯虚构技术验收，仅整理已审核专业评估建议。' });
  const rows = Object.values(annual.data).flatMap(v => v?.records || []);
  evidence.annualAttempts = [...(evidence.annualAttempts || []), annual];
  fs.writeFileSync(evidenceFile, JSON.stringify(evidence, null, 2));
  assert.ok(rows.some(r => r.items === '血常规' && r.time === evidence.reportDrafts[0].date));
  assert.ok(rows.every(r => !/空腹|停药|禁食/.test(r.precautions || '')));
  assert.ok(rows.every(r => r.basisSummary));
  assert.ok(!annual.data.annual_checkup?.enabled, 'No unsupported annual package');
  evidence.initialAnnualQualityIssue = 'Initial output invented preparation instructions and generic checkup package; retained in earlier annual evidence, not published.';
  evidence.correctedAnnual = annual;
  let saved = await api(`/staff/patients/${s.patientId}/annual-plan`, 'PUT', { year, planType: 'jygj_prevention', templateId, moduleData: annual.data, notes: '纯虚构AI入口验收，非医疗建议' });
  assert.equal(saved.data.reviewStatus, 'pending');
  await login('healthManager');
  await api(`/staff/patients/${s.patientId}/annual-plan/push?year=${year}&planType=jygj_prevention`, 'PATCH', {}, 403);
  await login('familyDoctor');
  saved = await api(`/staff/patients/${s.patientId}/annual-plan/push?year=${year}&planType=jygj_prevention`, 'PATCH', {});
  assert.equal(saved.data.reviewStatus, 'approved');
  const again = await api(`/staff/patients/${s.patientId}/annual-plan?year=${year}&planType=jygj_prevention`, 'GET');
  assert.equal(again.data._id, saved.data._id);
  evidence.annualPlanId = saved.data._id; evidence.annualSavedReviewed = true;
  evidence.usage = await m.connection.db.collection('ai_usage').find({}, { projection: { provider: 1, model: 1, status: 1, actualTokens: 1, inputTokens: 1, outputTokens: 1 } }).toArray();
  fs.writeFileSync(evidenceFile, JSON.stringify(evidence, null, 2));
  console.log('PASS live annual source-bound content, pending save, unauthorized403, advisor approval, reload');
  console.log('USAGE',JSON.stringify(evidence.usage));
})().catch(e => { console.error(e.message); process.exitCode=1; }).finally(()=>m.disconnect());
