// A source change creates a review task; it never changes a clinical rule.
const RULE_VERSION = '2026-10-03.1';
const standards = [
  { id: 'c-tirads', title: 'C-TIRADS 甲状腺结节分类', kind: 'guideline', version: '2020', ruleVersion: RULE_VERSION, sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/32827126/', originalUrl: 'https://master.yiigle.com/uploads/guide_html/2020%E7%94%B2%E7%8A%B6%E8%85%BA%E7%BB%93%E8%8A%82%E8%B6%85%E5%A3%B0%E6%81%B6%E6%80%A7%E5%8D%B1%E9%99%A9%E5%88%86%E5%B1%82%E4%B8%AD%E5%9B%BD%E6%8C%87%E5%8D%97%EF%BC%9AC-TIRADS%20-%20%E4%B8%AD%E5%8D%8E%E8%B6%85%E5%A3%B0%E5%BD%B1%E5%83%8F%E5%AD%A6%E6%9D%82%E5%BF%97.html', origin: '国内', publisher: '中华超声影像学杂志', evidence: 'full', currentRule: '从双重审核报告提取明确写出的类别，不自行计算。', implementation: 'shared/standardDiseaseAssessment.cjs', monitor: 'source' },
  { id: 'acr-tirads', title: 'ACR TI-RADS 甲状腺结节分类', kind: 'guideline', version: '2017', ruleVersion: RULE_VERSION, sourceUrl: 'https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Reporting-and-Data-Systems/TI-RADS', originalUrl: 'https://cs.acr.org/-/media/ACR/Files/RADS/TI-RADS/TI-RADS-Alternative-chart.pdf', origin: '海外', publisher: '美国放射学会（ACR）', evidence: 'full', currentRule: '从双重审核报告提取明确写出的类别，不自行计算。', implementation: 'shared/standardDiseaseAssessment.cjs', monitor: 'source' },
  { id: 'bi-rads', title: 'ACR BI-RADS 乳腺影像分类', kind: 'guideline', version: '版次待核对', ruleVersion: RULE_VERSION, sourceUrl: 'https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Reporting-and-Data-Systems/BI-RADS', originalUrl: 'https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Reporting-and-Data-Systems/BI-RADS', origin: '海外', publisher: '美国放射学会（ACR）', evidence: 'restricted', evidenceNote: 'ACR 已发布 v2025；完整手册需访问权限，现行规则未记录版次。', currentRule: '从双重审核报告提取明确写出的类别；版次待核对。', implementation: 'shared/standardDiseaseAssessment.cjs', monitor: 'source' },
  { id: 'lung-rads', title: 'ACR Lung-RADS 肺结节分类', kind: 'guideline', version: 'v2022', ruleVersion: RULE_VERSION, sourceUrl: 'https://edge.sitecorecloud.io/americancoldf5f-acrorgf92a-productioncb02-3650/media/ACR/Files/RADS/Lung-RADS/Lung-RADS-2022.pdf', originalUrl: 'https://edge.sitecorecloud.io/americancoldf5f-acrorgf92a-productioncb02-3650/media/ACR/Files/RADS/Lung-RADS/Lung-RADS-2022.pdf', origin: '海外', publisher: '美国放射学会（ACR）', evidence: 'full', currentRule: '从双重审核报告提取明确写出的类别，不自行计算。', implementation: 'shared/standardDiseaseAssessment.cjs', monitor: 'source' },
  { id: 'cn-lipid-2023', title: '中国血脂管理指南：ASCVD 风险评估', kind: 'guideline', version: '2023', ruleVersion: '2026-07-06', sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/36925135/', originalUrl: 'https://csc.cma.org.cn/attach/0/96b4e603cee74b7fb208b278aa92bd8b.pdf', origin: '国内', publisher: '中国血脂管理指南修订联合专家委员会', evidence: 'full', currentRule: '按代码内的 2023 指南风险分层表评估；具体分支需对照原文。', implementation: 'backend/src/utils/ascvdRisk.js', monitor: 'source' },
  { id: 'phq9', title: 'PHQ-9 抑郁症状量表', kind: 'instrument', version: '2001', sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/11556941/', originalUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1495268/', origin: '海外', publisher: 'Kroenke 等，J Gen Intern Med', evidence: 'full', currentRule: '9 题各 0–3 分；总分以 5、10、15、20 为分层界点。', implementation: 'backend/src/config/psychScales.js', monitor: 'manual' },
  { id: 'gad7', title: 'GAD-7 焦虑症状量表', kind: 'instrument', version: '2006', sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/16717171/', originalUrl: 'https://doi.org/10.1001/archinte.166.10.1092', origin: '海外', publisher: 'Spitzer 等，Arch Intern Med', evidence: 'restricted', evidenceNote: '已核对出版记录；原文访问可能受期刊权限限制。', currentRule: '7 题各 0–3 分；总分以 5、10、15 为分层界点。', implementation: 'backend/src/config/psychScales.js', monitor: 'manual' },
  { id: 'scl90-sas-sds', title: 'SCL-90 / SAS / SDS 量表导入与阈值', kind: 'instrument', version: '待核对', sourceUrl: '', originalUrl: '', origin: '海外量表／国内阈值待核对', publisher: '原量表及国内常模出处待补证', evidence: 'missing', evidenceNote: '未找到能支持三量表现行阈值的原件；当前 SAS 与 SDS 共用 53 分，需分别核对。', currentRule: 'SCL-90 因子均分分层；SAS、SDS 标准分＝粗分×1.25，均以 ≥53 标记异常。', implementation: 'backend/src/utils/psychScaleImport.js', monitor: 'manual' },
  { id: 'health-score', title: '基础健康评分与慢病扣分', kind: 'internal', version: '内部规则', sourceUrl: '', originalUrl: '', origin: '嘉医汇内部', publisher: '制定者待确认', evidence: 'missing', evidenceNote: '代码引用“健康评分逻辑.docx”，仓库未找到签发原件。', currentRule: '基础分、生活方式分及慢病三级扣分表组合为总分。', implementation: 'backend/src/utils/healthScore.js', monitor: 'manual' },
  { id: 'cancer-screening', title: '癌症筛查覆盖口径', kind: 'internal', version: '内部规则', sourceUrl: '', originalUrl: '', origin: '嘉医汇内部', publisher: '制定者待确认', evidence: 'missing', evidenceNote: '代码注明“金娟口径，2026-07-10 确认”，仓库未找到批准记录或原件。', currentRule: '按部位、年龄和性别判断筛查覆盖及替代条件。', implementation: 'backend/src/config/cancerScreeningRules.js', monitor: 'manual' },
];
module.exports = { RULE_VERSION, standards };
