// ── 专项筛查分类树（前后端单一数据源）──────────────────────────────
// 与 app/src/screens/records/SpecialScreeningScreen.js 的 CATALOG 完全对齐。
// screeningKey(id) 格式：`<短码>|<二级parent>|<检查项label>`，短码：tumor/cardio/chronic/hp/other。
// 每个叶子节点附 aliases（OCR/报告常见别名），用于自动归类匹配；批次2 持续按真实报告样本补充。

const NODES = [
  // ── 肿瘤风险筛查（tumor）──────────────────────────────────────────
  { id: 'tumor|肺癌|肺CT', category: 'tumor', categoryKey: 'tumor', parent: '肺癌', label: '肺CT', itemType: 'imaging', gender: null,
    aliases: ['胸部CT', '肺部CT', '低剂量螺旋CT', '低剂量胸部CT', '胸部低剂量CT', '肺部螺旋CT', '胸部平扫CT', '胸部CT平扫'] },
  { id: 'tumor|结直肠癌|粪便隐血', category: 'tumor', categoryKey: 'tumor', parent: '结直肠癌', label: '粪便隐血', itemType: 'lab', gender: null,
    aliases: ['便潜血', '大便隐血', '粪便潜血', 'OB', '便隐血'] },
  { id: 'tumor|结直肠癌|粪便基因检测', category: 'tumor', categoryKey: 'tumor', parent: '结直肠癌', label: '粪便基因检测', itemType: 'lab', gender: null,
    aliases: ['肠癌基因检测', '粪便DNA检测', '便基因检测'] },
  { id: 'tumor|结直肠癌|肠镜', category: 'tumor', categoryKey: 'tumor', parent: '结直肠癌', label: '肠镜', itemType: 'imaging', gender: null,
    aliases: ['结肠镜', '电子肠镜', '纤维结肠镜', '电子结肠镜', '全结肠镜'] },
  { id: 'tumor|结直肠癌|肠镜病理', category: 'tumor', categoryKey: 'tumor', parent: '结直肠癌', label: '肠镜病理', itemType: 'imaging', gender: null,
    aliases: ['肠镜活检', '结肠镜病理', '肠道病理'] },
  { id: 'tumor|肝癌|乙肝三系', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: '乙肝三系', itemType: 'lab', gender: null,
    aliases: ['乙肝两对半', '乙型肝炎表面抗原', '乙肝五项', 'HBsAg'] },
  { id: 'tumor|肝癌|HBV-DNA', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: 'HBV-DNA', itemType: 'lab', gender: null,
    aliases: ['乙肝病毒DNA', '乙肝DNA', 'HBVDNA'] },
  { id: 'tumor|肝癌|丙肝两项', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: '丙肝两项', itemType: 'lab', gender: null,
    aliases: ['丙肝抗体', '丙型肝炎抗体', 'HCV'] },
  { id: 'tumor|肝癌|肝脏超声', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: '肝脏超声', itemType: 'imaging', gender: null,
    aliases: ['肝胆胰脾超声', '肝胆脾超声', '上腹部超声', '肝脏彩超', '肝胆彩超', '腹部彩超', '肝胆胰脾彩超'] },
  { id: 'tumor|肝癌|肝脏磁共振', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: '肝脏磁共振', itemType: 'imaging', gender: null,
    aliases: ['肝脏MRI', '上腹部MRI', '肝脏核磁'] },
  { id: 'tumor|肝癌|肝脏纤维弹性超声', category: 'tumor', categoryKey: 'tumor', parent: '肝癌', label: '肝脏纤维弹性超声', itemType: 'imaging', gender: null,
    aliases: ['肝脏弹性成像', 'FibroScan', '肝纤维化扫描', '肝脏硬度检测'] },
  { id: 'tumor|胃癌|碳13呼气试验', category: 'tumor', categoryKey: 'tumor', parent: '胃癌', label: '碳13呼气试验', itemType: 'lab', gender: null,
    aliases: ['C13呼气试验', '幽门螺杆菌呼气试验', '碳14呼气试验', 'C14呼气试验', 'C13', '尿素呼气试验'] },
  { id: 'tumor|胃癌|胃蛋白酶原', category: 'tumor', categoryKey: 'tumor', parent: '胃癌', label: '胃蛋白酶原', itemType: 'lab', gender: null,
    aliases: ['胃蛋白酶原I', '胃蛋白酶原II', 'PGI', 'PGII', 'PG'] },
  { id: 'tumor|胃癌|胃泌素', category: 'tumor', categoryKey: 'tumor', parent: '胃癌', label: '胃泌素', itemType: 'lab', gender: null,
    aliases: ['胃泌素17', 'G-17', 'G17'] },
  { id: 'tumor|胃癌|胃镜', category: 'tumor', categoryKey: 'tumor', parent: '胃癌', label: '胃镜', itemType: 'imaging', gender: null,
    aliases: ['电子胃镜', '上消化道内镜', '胃十二指肠镜', '无痛胃镜'] },
  { id: 'tumor|胃癌|胃镜病理', category: 'tumor', categoryKey: 'tumor', parent: '胃癌', label: '胃镜病理', itemType: 'imaging', gender: null,
    aliases: ['胃镜活检', '胃黏膜病理'] },
  { id: 'tumor|食管癌|胃食管镜', category: 'tumor', categoryKey: 'tumor', parent: '食管癌', label: '胃食管镜', itemType: 'imaging', gender: null,
    aliases: ['食管镜', '食道镜'] },
  { id: 'tumor|食管癌|食管镜病理', category: 'tumor', categoryKey: 'tumor', parent: '食管癌', label: '食管镜病理', itemType: 'imaging', gender: null,
    aliases: ['食管活检', '食道病理'] },
  { id: 'tumor|前列腺癌|前列腺超声', category: 'tumor', categoryKey: 'tumor', parent: '前列腺癌', label: '前列腺超声', itemType: 'imaging', gender: '男',
    aliases: ['前列腺彩超', '经直肠前列腺超声'] },
  { id: 'tumor|乳腺癌|乳腺超声', category: 'tumor', categoryKey: 'tumor', parent: '乳腺癌', label: '乳腺超声', itemType: 'imaging', gender: '女',
    aliases: ['乳腺彩超', '双侧乳腺超声', '乳房超声'] },
  { id: 'tumor|乳腺癌|乳腺钼靶', category: 'tumor', categoryKey: 'tumor', parent: '乳腺癌', label: '乳腺钼靶', itemType: 'imaging', gender: '女',
    aliases: ['钼靶', '乳腺X线', '乳腺X线摄影', '乳腺钼钯'] },
  { id: 'tumor|乳腺癌|乳腺磁共振', category: 'tumor', categoryKey: 'tumor', parent: '乳腺癌', label: '乳腺磁共振', itemType: 'imaging', gender: '女',
    aliases: ['乳腺MRI', '乳腺核磁'] },
  { id: 'tumor|宫颈癌|HPV', category: 'tumor', categoryKey: 'tumor', parent: '宫颈癌', label: 'HPV', itemType: 'lab', gender: '女',
    aliases: ['人乳头瘤病毒', 'HPV分型', 'HPV-DNA', '人乳头状瘤病毒'] },
  { id: 'tumor|宫颈癌|TCT', category: 'tumor', categoryKey: 'tumor', parent: '宫颈癌', label: 'TCT', itemType: 'lab', gender: '女',
    aliases: ['宫颈液基细胞学', '液基薄层细胞学', 'LCT', '宫颈细胞学'] },
  { id: 'tumor|子宫内膜癌|阴道超声', category: 'tumor', categoryKey: 'tumor', parent: '子宫内膜癌/卵巢癌', label: '阴道超声', itemType: 'imaging', gender: '女',
    aliases: ['经阴道超声', '阴超', '妇科超声', '子宫附件超声', '盆腔超声'] },
  { id: 'tumor|甲状腺癌|甲状腺超声', category: 'tumor', categoryKey: 'tumor', parent: '甲状腺癌', label: '甲状腺超声', itemType: 'imaging', gender: null,
    aliases: ['甲状腺彩超', '甲状腺及颈部淋巴结超声'] },
  { id: 'tumor|甲状腺癌|甲状腺穿刺', category: 'tumor', categoryKey: 'tumor', parent: '甲状腺癌', label: '甲状腺穿刺', itemType: 'imaging', gender: null,
    aliases: ['甲状腺细针穿刺', 'FNA', '甲状腺活检'] },
  { id: 'tumor|膀胱癌|尿常规', category: 'tumor', categoryKey: 'tumor', parent: '膀胱癌', label: '尿常规', itemType: 'lab', gender: null,
    aliases: ['尿液分析', '尿液常规'] },
  { id: 'tumor|膀胱癌|膀胱超声', category: 'tumor', categoryKey: 'tumor', parent: '膀胱癌', label: '膀胱超声', itemType: 'imaging', gender: null,
    aliases: ['膀胱彩超', '泌尿系超声'] },
  { id: 'tumor|胰腺癌|胰腺超声', category: 'tumor', categoryKey: 'tumor', parent: '胰腺癌', label: '胰腺超声', itemType: 'imaging', gender: null,
    aliases: ['胰腺彩超'] },
  { id: 'tumor|胰腺癌|胰腺MRI', category: 'tumor', categoryKey: 'tumor', parent: '胰腺癌', label: '胰腺MRI', itemType: 'imaging', gender: null,
    aliases: ['胰腺磁共振', '胰腺核磁', 'MRCP'] },
  { id: 'tumor|淋巴瘤|淋巴结超声', category: 'tumor', categoryKey: 'tumor', parent: '淋巴瘤', label: '淋巴结超声', itemType: 'imaging', gender: null,
    aliases: ['淋巴结彩超', '浅表淋巴结超声'] },
  { id: 'tumor|淋巴瘤|淋巴结磁共振', category: 'tumor', categoryKey: 'tumor', parent: '淋巴瘤', label: '淋巴结磁共振', itemType: 'imaging', gender: null,
    aliases: ['淋巴结MRI'] },
  { id: 'tumor|鼻咽癌|EB病毒IgA', category: 'tumor', categoryKey: 'tumor', parent: '鼻咽癌', label: 'EB病毒IgA', itemType: 'lab', gender: null,
    aliases: ['EB病毒衣壳抗原IgA', 'EBV-IgA', 'VCA-IgA'] },
  { id: 'tumor|鼻咽癌|EB病毒IgM', category: 'tumor', categoryKey: 'tumor', parent: '鼻咽癌', label: 'EB病毒IgM', itemType: 'lab', gender: null,
    aliases: ['EBV-IgM'] },
  { id: 'tumor|鼻咽癌|EB病毒IgG', category: 'tumor', categoryKey: 'tumor', parent: '鼻咽癌', label: 'EB病毒IgG', itemType: 'lab', gender: null,
    aliases: ['EBV-IgG'] },
  { id: 'tumor|鼻咽癌|鼻咽镜', category: 'tumor', categoryKey: 'tumor', parent: '鼻咽癌', label: '鼻咽镜', itemType: 'imaging', gender: null,
    aliases: ['电子鼻咽镜', '鼻内镜'] },
  { id: 'tumor|肾癌|肾脏超声', category: 'tumor', categoryKey: 'tumor', parent: '肾癌', label: '肾脏超声', itemType: 'imaging', gender: null,
    aliases: ['肾脏彩超', '双肾超声', '泌尿系彩超', '双肾输尿管膀胱超声'] },
  { id: 'tumor|肿瘤标志物|甲胎蛋白', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: '甲胎蛋白', itemType: 'lab', gender: null,
    aliases: ['AFP'] },
  { id: 'tumor|肿瘤标志物|癌胚抗原', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: '癌胚抗原', itemType: 'lab', gender: null,
    aliases: ['CEA'] },
  { id: 'tumor|肿瘤标志物|铁蛋白', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: '铁蛋白', itemType: 'lab', gender: null,
    aliases: ['血清铁蛋白', 'SF', 'Ferritin'] },
  { id: 'tumor|肿瘤标志物|CA125', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'CA125', itemType: 'lab', gender: '女',
    aliases: ['糖类抗原125', 'CA-125'] },
  { id: 'tumor|肿瘤标志物|CA19-9', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'CA19-9', itemType: 'lab', gender: null,
    aliases: ['CA199', '糖类抗原199', 'CA-199', '糖类抗原19-9'] },
  { id: 'tumor|肿瘤标志物|SCC', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'SCC', itemType: 'lab', gender: null,
    aliases: ['鳞状细胞癌抗原', '鳞癌抗原', 'SCCA'] },
  { id: 'tumor|肿瘤标志物|NSE', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'NSE', itemType: 'lab', gender: null,
    aliases: ['神经元特异性烯醇化酶'] },
  { id: 'tumor|肿瘤标志物|CYFRA21-1', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'CYFRA21-1', itemType: 'lab', gender: null,
    aliases: ['细胞角蛋白19片段', '细胞角蛋白片段', 'CYFRA211'] },
  { id: 'tumor|肿瘤标志物|ProGRP', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'ProGRP', itemType: 'lab', gender: null,
    aliases: ['胃泌素释放肽前体'] },
  { id: 'tumor|肿瘤标志物|T-PSA', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'T-PSA', itemType: 'lab', gender: '男',
    aliases: ['总PSA', 'tPSA', '总前列腺特异性抗原', 'PSA'] },
  { id: 'tumor|肿瘤标志物|F-PSA', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'F-PSA', itemType: 'lab', gender: '男',
    aliases: ['游离PSA', 'fPSA', '游离前列腺特异性抗原'] },
  { id: 'tumor|肿瘤标志物|fPSA/tPSA', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'fPSA/tPSA', itemType: 'lab', gender: '男',
    aliases: ['PSA比值', '游离总PSA比值'] },
  { id: 'tumor|肿瘤标志物|TSGF', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'TSGF', itemType: 'lab', gender: null,
    aliases: ['恶性肿瘤特异性生长因子'] },
  { id: 'tumor|肿瘤标志物|HCG', category: 'tumor', categoryKey: 'tumor', parent: '肿瘤标志物', label: 'HCG', itemType: 'lab', gender: null,
    aliases: ['人绒毛膜促性腺激素', 'β-HCG', 'βHCG'] },

  // ── 心脑血管病风险筛查（cardio）──────────────────────────────────
  { id: 'cardio|心脏筛查|脂蛋白磷脂酶A2', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '脂蛋白磷脂酶A2', itemType: 'lab', gender: null,
    aliases: ['Lp-PLA2', 'LpPLA2', '脂蛋白相关磷脂酶A2'] },
  { id: 'cardio|心脏筛查|常规心电图', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '常规心电图', itemType: 'imaging', gender: null,
    aliases: ['心电图', 'ECG', 'EKG', '十二导联心电图', '12导联心电图', '静息心电图'] },
  { id: 'cardio|心脏筛查|动态心电图', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '动态心电图', itemType: 'imaging', gender: null,
    aliases: ['Holter', '24小时动态心电图', '霍尔特'] },
  { id: 'cardio|心脏筛查|心脏超声', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '心脏超声', itemType: 'imaging', gender: null,
    aliases: ['心脏彩超', '超声心动图', '心脏彩色多普勒', '心动超声', '心脏多普勒超声'] },
  { id: 'cardio|心脏筛查|冠脉CTA', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '冠脉CTA', itemType: 'imaging', gender: null,
    aliases: ['冠状动脉CTA', '冠脉CT', '冠状动脉CT血管成像'] },
  { id: 'cardio|心脏筛查|心脏磁共振', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '心脏磁共振', itemType: 'imaging', gender: null,
    aliases: ['心脏MRI', '心脏核磁'] },
  { id: 'cardio|心脏筛查|运动平板', category: 'cardio', categoryKey: 'cardiovascular', parent: '心脏筛查', label: '运动平板', itemType: 'imaging', gender: null,
    aliases: ['运动平板试验', '平板运动试验', '运动负荷试验'] },
  { id: 'cardio|大脑筛查|同型半胱氨酸', category: 'cardio', categoryKey: 'cardiovascular', parent: '大脑筛查', label: '同型半胱氨酸', itemType: 'lab', gender: null,
    aliases: ['Hcy', '同型半胱胺酸', '血同型半胱氨酸'] },
  { id: 'cardio|大脑筛查|颈动脉超声', category: 'cardio', categoryKey: 'cardiovascular', parent: '大脑筛查', label: '颈动脉超声', itemType: 'imaging', gender: null,
    aliases: ['颈动脉彩超', '双侧颈动脉超声', '颈部血管超声', '颈动脉血管彩超'] },
  { id: 'cardio|大脑筛查|头颅MRI', category: 'cardio', categoryKey: 'cardiovascular', parent: '大脑筛查', label: '头颅MRI', itemType: 'imaging', gender: null,
    aliases: ['颅脑MRI', '头颅磁共振', '脑MRI', '头部核磁'] },
  { id: 'cardio|大脑筛查|颅脑MRA', category: 'cardio', categoryKey: 'cardiovascular', parent: '大脑筛查', label: '颅脑MRA', itemType: 'imaging', gender: null,
    aliases: ['头颅MRA', '脑血管MRA', '颅内动脉MRA'] },
  { id: 'cardio|其他|动脉硬化测定', category: 'cardio', categoryKey: 'cardiovascular', parent: '其他', label: '动脉硬化测定', itemType: 'imaging', gender: null,
    aliases: ['动脉硬化检测', 'PWV', 'ABI', '脉搏波传导速度', '踝臂指数'] },

  // ── 慢性病筛查（chronic）─────────────────────────────────────────
  { id: 'chronic|高血压|血压', category: 'chronic', categoryKey: 'chronic', parent: '高血压筛查', label: '血压', itemType: 'lab', gender: null,
    aliases: ['血压测量', '诊室血压'] },
  { id: 'chronic|高血压|动态血压', category: 'chronic', categoryKey: 'chronic', parent: '高血压筛查', label: '动态血压', itemType: 'imaging', gender: null,
    aliases: ['24小时动态血压', '动态血压监测', 'ABPM'] },
  { id: 'chronic|糖尿病|空腹血糖', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '空腹血糖', itemType: 'lab', gender: null,
    aliases: ['葡萄糖', 'GLU', 'FPG', '空腹葡萄糖', '血糖', '空腹血浆葡萄糖'] },
  { id: 'chronic|糖尿病|糖化血红蛋白', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '糖化血红蛋白', itemType: 'lab', gender: null,
    aliases: ['HbA1c', '糖化血红蛋白A1c', 'A1C', '糖化'] },
  { id: 'chronic|糖尿病|空腹胰岛素', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '空腹胰岛素', itemType: 'lab', gender: null,
    aliases: ['胰岛素', 'FINS', '空腹INS'] },
  { id: 'chronic|糖尿病|空腹C肽', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '空腹C肽', itemType: 'lab', gender: null,
    aliases: ['C肽', 'C-肽', '空腹C-P'] },
  { id: 'chronic|糖尿病|30分钟胰岛素C肽', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '30分钟胰岛素/C肽', itemType: 'lab', gender: null,
    aliases: ['0.5小时胰岛素', '30min胰岛素'] },
  { id: 'chronic|糖尿病|1小时胰岛素C肽', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '1小时胰岛素/C肽', itemType: 'lab', gender: null,
    aliases: ['1h胰岛素', '1小时胰岛素'] },
  { id: 'chronic|糖尿病|2小时胰岛素C肽', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '2小时胰岛素/C肽', itemType: 'lab', gender: null,
    aliases: ['2h胰岛素', '餐后2小时胰岛素'] },
  { id: 'chronic|糖尿病|3小时胰岛素C肽', category: 'chronic', categoryKey: 'chronic', parent: '糖尿病筛查', label: '3小时胰岛素/C肽', itemType: 'lab', gender: null,
    aliases: ['3h胰岛素', '3小时胰岛素'] },
  { id: 'chronic|肝功能|肝功', category: 'chronic', categoryKey: 'chronic', parent: '肝脏功能评估', label: '肝功', itemType: 'lab', gender: null,
    aliases: ['肝功能', '肝功能全套', '肝功能检查', 'ALT', 'AST', '谷丙转氨酶', '谷草转氨酶', '肝功七项'] },
  { id: 'chronic|肾功能|肾功能', category: 'chronic', categoryKey: 'chronic', parent: '肾脏功能评估', label: '肾功能', itemType: 'lab', gender: null,
    aliases: ['肾功', '肾功能检查', '肌酐', '尿素氮', '血肌酐', 'Cr', 'BUN'] },
  { id: 'chronic|肾功能|尿微量白蛋白', category: 'chronic', categoryKey: 'chronic', parent: '肾脏功能评估', label: '尿微量白蛋白', itemType: 'lab', gender: null,
    aliases: ['微量白蛋白', 'mALB', '尿白蛋白'] },
  { id: 'chronic|肾功能|尿肌酐', category: 'chronic', categoryKey: 'chronic', parent: '肾脏功能评估', label: '尿肌酐', itemType: 'lab', gender: null,
    aliases: ['尿肌酐定量', 'UCr'] },
  { id: 'chronic|肾功能|尿微量白蛋白尿肌酐', category: 'chronic', categoryKey: 'chronic', parent: '肾脏功能评估', label: '尿微量白蛋白/尿肌酐', itemType: 'lab', gender: null,
    aliases: ['尿微量白蛋白肌酐比', 'ACR', '尿白蛋白肌酐比值'] },
  { id: 'chronic|甲状腺|甲状腺功能7项', category: 'chronic', categoryKey: 'chronic', parent: '甲状腺功能评估', label: '甲状腺功能7项', itemType: 'lab', gender: null,
    aliases: ['甲功七项', '甲状腺功能', '甲功', '甲功五项', '甲功三项', 'TSH', 'FT3', 'FT4', '甲状腺功能五项'] },
  { id: 'chronic|甲状腺|甲状腺球蛋白', category: 'chronic', categoryKey: 'chronic', parent: '甲状腺功能评估', label: '甲状腺球蛋白', itemType: 'lab', gender: null,
    aliases: ['Tg', '甲状腺球蛋白抗体', 'TgAb'] },
  { id: 'chronic|老年痴呆|综合筛查', category: 'chronic', categoryKey: 'chronic', parent: '老年痴呆筛查', label: '综合筛查', itemType: 'lab', gender: null,
    aliases: ['认知功能筛查', 'MMSE', '阿尔茨海默筛查'] },
  { id: 'chronic|骨质疏松|综合筛查', category: 'chronic', categoryKey: 'chronic', parent: '骨质疏松筛查', label: '综合筛查', itemType: 'imaging', gender: null,
    aliases: ['骨密度', '骨密度检测', '骨密度测定', 'BMD', '双能X线骨密度'] },
  { id: 'chronic|更年期|综合筛查', category: 'chronic', categoryKey: 'chronic', parent: '更年期筛查', label: '综合筛查', itemType: 'lab', gender: null,
    aliases: ['性激素六项', '性激素', 'FSH', 'LH', '雌二醇'] },

  // ── 健康促进筛查（hp）────────────────────────────────────────────
  { id: 'hp|特殊检测|慢性食物过敏检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '慢性食物过敏检测', itemType: 'lab', gender: null,
    aliases: ['食物不耐受', '食物特异性IgG', '食物过敏原'] },
  { id: 'hp|特殊检测|肠道菌群基因测序', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '肠道菌群基因测序', itemType: 'lab', gender: null,
    aliases: ['肠道菌群检测', '肠道微生态', '菌群测序'] },
  { id: 'hp|特殊检测|端粒长度检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '端粒长度检测', itemType: 'lab', gender: null,
    aliases: ['端粒检测'] },
  { id: 'hp|特殊检测|精准基因检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '精准基因检测', itemType: 'lab', gender: null,
    aliases: ['基因检测', '遗传基因检测'] },
  { id: 'hp|特殊检测|性别荷尔蒙检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '性别荷尔蒙检测', itemType: 'lab', gender: null,
    aliases: ['性激素检测', '性荷尔蒙'] },
  { id: 'hp|特殊检测|环境荷尔蒙检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '环境荷尔蒙检测', itemType: 'lab', gender: null,
    aliases: ['环境激素'] },
  { id: 'hp|特殊检测|抗压力荷尔蒙检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '抗压力荷尔蒙检测', itemType: 'lab', gender: null,
    aliases: ['皮质醇', '压力激素', '抗压荷尔蒙'] },
  { id: 'hp|特殊检测|抗氧化维生素检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '抗氧化维生素检测', itemType: 'lab', gender: null,
    aliases: ['抗氧化维生素', '维生素谱'] },
  { id: 'hp|特殊检测|全套新陈代谢分析', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '全套新陈代谢分析', itemType: 'lab', gender: null,
    aliases: ['代谢分析', '新陈代谢检测'] },
  { id: 'hp|特殊检测|营养与重金属元素', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '营养与重金属元素', itemType: 'lab', gender: null,
    aliases: ['重金属检测', '微量元素', '营养元素检测', '重金属元素'] },
  { id: 'hp|特殊检测|生长因子分析', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '生长因子分析', itemType: 'lab', gender: null,
    aliases: ['IGF-1', '生长因子'] },
  { id: 'hp|特殊检测|雌激素代谢分析', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '雌激素代谢分析', itemType: 'lab', gender: null,
    aliases: ['雌激素代谢'] },
  { id: 'hp|特殊检测|氧化压力分析', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '氧化压力分析', itemType: 'lab', gender: null,
    aliases: ['氧化应激', '氧化压力检测'] },
  { id: 'hp|特殊检测|尿碘检测', category: 'hp', categoryKey: 'health_promote', parent: '特殊检测', label: '尿碘检测', itemType: 'lab', gender: null,
    aliases: ['尿碘'] },

  // ── 其他筛查（other）─────────────────────────────────────────────
  { id: 'other|基础检查|血常规', category: 'other', categoryKey: 'other', parent: '基础检查', label: '血常规', itemType: 'lab', gender: null,
    aliases: ['血细胞分析', '全血细胞计数', 'CBC', '血常规检查', '血液分析'] },
  { id: 'other|基础检查|电解质', category: 'other', categoryKey: 'other', parent: '基础检查', label: '电解质', itemType: 'lab', gender: null,
    aliases: ['电解质检查', '血钾', '血钠', '血氯', '钾钠氯'] },
  { id: 'other|基础检查|25羟基维生素D', category: 'other', categoryKey: 'other', parent: '基础检查', label: '25-羟基维生素D', itemType: 'lab', gender: null,
    aliases: ['维生素D', '25(OH)D', '25羟维生素D', 'VitD', '25-羟维生素D3'] },
  { id: 'other|基础检查|凝血功能', category: 'other', categoryKey: 'other', parent: '基础检查', label: '凝血功能', itemType: 'lab', gender: null,
    aliases: ['凝血四项', '凝血五项', 'PT', 'APTT', '凝血常规'] },
  { id: 'other|基础检查|D二聚体', category: 'other', categoryKey: 'other', parent: '基础检查', label: 'D-二聚体', itemType: 'lab', gender: null,
    aliases: ['D二聚体', 'D-Dimer', 'DDimer'] },
  { id: 'other|基础检查|传染病4项', category: 'other', categoryKey: 'other', parent: '基础检查', label: '传染病4项', itemType: 'lab', gender: null,
    aliases: ['传染病四项', '术前八项', '感染四项', '乙肝丙肝梅毒艾滋'] },
];

// 按一级分类聚合成树（供前端 GET /staff/screening-tree 使用）
function buildTree() {
  const catOrder = ['tumor', 'cardio', 'chronic', 'hp', 'other'];
  const catLabel = { tumor: '肿瘤风险筛查', cardio: '心脑血管病风险筛查', chronic: '慢性病筛查', hp: '健康促进筛查', other: '其他筛查' };
  const byCat = {};
  NODES.forEach(n => {
    if (!byCat[n.category]) byCat[n.category] = {};
    if (!byCat[n.category][n.parent]) byCat[n.category][n.parent] = [];
    byCat[n.category][n.parent].push({ id: n.id, label: n.label, itemType: n.itemType, gender: n.gender });
  });
  return catOrder.filter(c => byCat[c]).map(c => ({
    category: c, categoryKey: NODES.find(n => n.category === c).categoryKey, label: catLabel[c],
    parents: Object.entries(byCat[c]).map(([parent, items]) => ({ parent, items })),
  }));
}

module.exports = { NODES, buildTree };
