import React, { useEffect, useState } from 'react'
import { adminAPI } from '../../api'
import { useToast } from '../../App'

const TYPES = { internal: '自有资源', external: '外采资源', joint: '联合交付' }
const blank = { name: '', resourceType: 'internal', serviceScope: '', cities: '', deliveryOwner: '', contactName: '', contactPhone: '', sla: '首次响应：1 个工作日内；资料核验：1 个工作日内；预约反馈：3 个工作日内；异常情况即时升级。', handoffChecklist: '会员基本信息与联系方式；服务需求说明；已取得授权的病历/检查资料；预约偏好与时间窗口；内部交接负责人。', procurementNote: '按合同约定结算、开票和改期规则执行；合同到期前 30 天复核。仅在存在例外条款时补充说明。', costPrice: 0, contractExpiresAt: '', status: 'active' }
const split = value => Array.isArray(value) ? value.join('、') : value || ''

export default function MedicalDeliveryResourcesPage() {
  const toast = useToast(); const [items, setItems] = useState([]); const [form, setForm] = useState(null); const [editing, setEditing] = useState(null)
  const load = async () => { try { const result = await adminAPI.medicalDeliveryResources(); setItems(result.data || []) } catch (error) { toast(error.message) } }
  useEffect(() => { load() }, [])
  const open = item => { setEditing(item || null); setForm({ ...blank, ...(item || {}), serviceScope: split(item?.serviceScope), cities: split(item?.cities), contractExpiresAt: item?.contractExpiresAt ? String(item.contractExpiresAt).slice(0, 10) : '' }) }
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const save = async () => { if (!form.name.trim()) return toast('请填写资源名称'); const payload = { ...form, serviceScope: form.serviceScope.split(/[、,，]/).map(x => x.trim()).filter(Boolean), cities: form.cities.split(/[、,，]/).map(x => x.trim()).filter(Boolean) }; try { editing ? await adminAPI.updateMedicalDeliveryResource(editing._id, payload) : await adminAPI.createMedicalDeliveryResource(payload); toast('服务资源已保存'); setForm(null); await load() } catch (error) { toast(error.message) } }
  return <div><div className="page-header"><div><div className="page-title">就医服务资源</div><div className="page-subtitle">配置自有、外采与联合交付资源；采购与合同信息仅供运营管理使用。</div></div><button className="btn btn-primary" onClick={() => open(null)}>＋ 新增服务资源</button></div><div className="card"><div className="card-body"><table className="table"><thead><tr><th>资源名称 / 类型</th><th>服务范围 / 城市</th><th>交付负责人</th><th>SLA</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item._id}><td><b>{item.name}</b><div style={{ fontSize: 12, color: '#729487' }}>{TYPES[item.resourceType]}</div></td><td>{split(item.serviceScope) || '-'}<div style={{ fontSize: 12, color: '#729487' }}>{split(item.cities)}</div></td><td>{item.deliveryOwner || item.contactName || '-'}</td><td>{item.sla || '-'}</td><td>{item.status === 'active' ? '启用' : '停用'}</td><td><button className="btn btn-secondary btn-sm" onClick={() => open(item)}>编辑</button> <button className="btn btn-secondary btn-sm" onClick={async () => { await adminAPI.toggleMedicalDeliveryResource(item._id); load() }}>{item.status === 'active' ? '停用' : '启用'}</button></td></tr>)}</tbody></table>{!items.length && <div style={{ padding: 36, textAlign: 'center', color: '#8AA89C' }}>暂无服务交付资源</div>}</div></div>{form && <div className="modal-overlay"><div className="modal" style={{ maxWidth: 760 }}><div className="modal-header"><h3 className="modal-title">{editing ? '编辑' : '新增'}服务资源</h3><button className="modal-close" onClick={() => setForm(null)}>×</button></div><div className="modal-body" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><Field label="资源名称 *" value={form.name} onChange={value => set('name', value)} /><Select label="资源类型" value={form.resourceType} onChange={value => set('resourceType', value)} options={Object.entries(TYPES)} /><Field label="服务范围" value={form.serviceScope} onChange={value => set('serviceScope', value)} placeholder="陪诊、翻译等，用顿号分隔" /><Field label="覆盖城市" value={form.cities} onChange={value => set('cities', value)} placeholder="杭州、上海等" /><Field label="交付负责人" value={form.deliveryOwner} onChange={value => set('deliveryOwner', value)} /><Field label="联系人电话" value={form.contactPhone} onChange={value => set('contactPhone', value)} /><Text label="统一 SLA / 时效（可按资源调整）" value={form.sla} onChange={value => set('sla', value)} /><Text label="统一交接清单（可增补）" value={form.handoffChecklist} onChange={value => set('handoffChecklist', value)} /><Text label="采购 / 合同例外备注（内部）" value={form.procurementNote} onChange={value => set('procurementNote', value)} /><Field label="采购成本（内部）" value={form.costPrice} onChange={value => set('costPrice', Number(value) || 0)} /><Field label="合同到期日" type="date" value={form.contractExpiresAt} onChange={value => set('contractExpiresAt', value)} /></div><div className="modal-footer"><button className="btn btn-secondary" onClick={() => setForm(null)}>取消</button><button className="btn btn-primary" onClick={save}>保存</button></div></div></div>}</div>
}
function Field({ label, value, onChange, placeholder = '', type = 'text' }) { return <div className="form-group"><label className="form-label">{label}</label><input className="form-input" type={type} value={value ?? ''} onChange={event => onChange(event.target.value)} placeholder={placeholder} /></div> }
function Text({ label, value, onChange }) { return <div className="form-group"><label className="form-label">{label}</label><textarea className="form-input" rows={3} value={value || ''} onChange={event => onChange(event.target.value)} /></div> }
function Select({ label, value, onChange, options }) { return <div className="form-group"><label className="form-label">{label}</label><select className="form-input" value={value} onChange={event => onChange(event.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></div> }
